import { StrategyType } from '../strategies/StrategyType';

// ── Types ────────────────────────────────────────────────────────────────────

export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'EXTREME';

export interface TradingPreset {
  id: string;
  name: string;
  description: string;
  riskLevel: RiskLevel;
  timeframe: string;
  strategyType: StrategyType;
  /** Flat config object — field names match the PUT /api/strategy body shape. */
  config: Record<string, unknown>;
}

// ── Active preset tracking ───────────────────────────────────────────────────

let activePresetId: string | null = null;

export function getActivePresetId(): string | null {
  return activePresetId;
}

export function setActivePresetId(id: string | null): void {
  activePresetId = id;
}

// ── Built-in presets ─────────────────────────────────────────────────────────

export const PRESETS: readonly TradingPreset[] = [
  {
    id: 'micro-grower',
    name: 'Micro Account Grower',
    description: 'High risk per trade on micro account with strict session windows and wide ATR stops.',
    riskLevel: 'EXTREME',
    timeframe: '15m',
    strategyType: 'CONSERVATIVE',
    config: {
      strategyType: 'CONSERVATIVE',
      emaFast: 9,
      emaSlow: 21,
      rsiPeriod: 14,
      rsiOverbought: 75,
      rsiOversold: 25,
      takeProfit: 30,
      stopLoss: 15,
      trailingStop: true,
      trailingStopPips: 10,
      riskPerTrade: 8,
      maxPositions: 1,
      dailyLossLimit: 15,
      maxDrawdown: 25,
      positionSizing: 'percentage',
      tradingHoursStart: '07:00',
      tradingHoursEnd: '15:00',
      timezone: 'UTC',
    },
  },
  {
    id: 'conservative-scalper',
    name: 'Conservative Scalper',
    description: 'Quick in-and-out with tight risk. Works during active sessions.',
    riskLevel: 'LOW',
    timeframe: '1m',
    strategyType: 'CONSERVATIVE',
    config: {
      strategyType: 'CONSERVATIVE',
      emaFast: 5,
      emaSlow: 13,
      rsiPeriod: 14,
      rsiOverbought: 70,
      rsiOversold: 30,
      takeProfit: 8,
      stopLoss: 5,
      trailingStop: true,
      trailingStopPips: 3,
      riskPerTrade: 1,
      maxPositions: 1,
      dailyLossLimit: 3,
      maxDrawdown: 10,
      positionSizing: 'percentage',
      tradingHoursStart: '08:00',
      tradingHoursEnd: '17:00',
      timezone: 'UTC',
    },
  },
  {
    id: 'london-breakout',
    name: 'London Breakout',
    description: 'One high-probability trade per day based on Asian range breakout.',
    riskLevel: 'MEDIUM',
    timeframe: '15m',
    strategyType: 'CONSERVATIVE',
    config: {
      strategyType: 'CONSERVATIVE',
      emaFast: 9,
      emaSlow: 21,
      rsiPeriod: 14,
      rsiOverbought: 70,
      rsiOversold: 30,
      takeProfit: 25,
      stopLoss: 15,
      trailingStop: true,
      trailingStopPips: 10,
      riskPerTrade: 2,
      maxPositions: 1,
      dailyLossLimit: 5,
      maxDrawdown: 15,
      positionSizing: 'percentage',
      tradingHoursStart: '07:00',
      tradingHoursEnd: '09:00',
      timezone: 'UTC',
    },
  },
  {
    id: 'trend-rider',
    name: 'Trend Rider',
    description: 'Catches bigger moves with fewer trades and higher conviction.',
    riskLevel: 'MEDIUM',
    timeframe: '15m',
    strategyType: 'CONSERVATIVE',
    config: {
      strategyType: 'CONSERVATIVE',
      emaFast: 21,
      emaSlow: 50,
      rsiPeriod: 14,
      rsiOverbought: 80,
      rsiOversold: 20,
      takeProfit: 40,
      stopLoss: 20,
      trailingStop: true,
      trailingStopPips: 15,
      riskPerTrade: 2,
      maxPositions: 2,
      dailyLossLimit: 5,
      maxDrawdown: 15,
      positionSizing: 'percentage',
      tradingHoursStart: '12:00',
      tradingHoursEnd: '15:00',
      timezone: 'UTC',
    },
  },
  {
    id: 'grid-scalper',
    name: 'Grid Scalper',
    description: 'Grid trading in ranging markets. Best during low-volatility Asian session.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'GRID_TRADING',
    config: {
      strategyType: 'GRID_TRADING',
      riskPerTrade: 0.5,
      maxPositions: 5,
      dailyLossLimit: 5,
      maxDrawdown: 10,
      positionSizing: 'percentage',
      tradingHoursStart: '00:00',
      tradingHoursEnd: '06:00',
      timezone: 'UTC',
      gridTrading: {
        gridLevels: 5,
        gridSpacing: 2.0,
        lotSizePerLevel: 10,
        takeProfitPerLevel: 1.0,
        maxGridDrawdown: 0.05,
        trendDetectionEnabled: true,
        trendAdxThreshold: 30,
      },
    },
  },

  // ── Synthetic Indices ──────────────────────────────────────────────────────
  {
    id: 'v100-1s-scalper',
    name: 'V100 (1s) Scalper',
    description: 'Mean reversion scalping on Volatility 100 (1s). 24/7, no session filter. Bollinger Band bounces.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'MEAN_REVERSION',
    config: {
      strategyType: 'MEAN_REVERSION',
      symbol: 'V100_1S',
      emaFast: 5,
      emaSlow: 13,
      rsiPeriod: 14,
      rsiOverbought: 75,
      rsiOversold: 25,
      useAtrStops: true,
      atrPeriod: 14,
      atrSlMultiplier: 1.5,
      atrTpMultiplier: 2.0,
      takeProfit: 20,
      stopLoss: 10,
      trailingStop: false,
      breakevenEnabled: true,
      breakevenTriggerPips: 8,
      spreadFilterPips: 0,
      minBodyPips: 0,
      sessionFilterEnabled: false,
      adxThreshold: 15,
      riskPerTrade: 2,
      maxPositions: 1,
      dailyLossLimit: 5,
      maxDrawdown: 15,
      positionSizing: 'percentage',
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      meanReversion: {
        bollingerPeriod: 20,
        bollingerStdDev: 2.0,
        rsiOversold: 25,
        rsiOverbought: 75,
        atrSlMultiplier: 1.5,
        atrTpMultiplier: 2.0,
      },
    },
  },
  {
    id: 'coin-flip-v100',
    name: 'Coin Flip V100 (1s)',
    description: 'Accumulator contracts on V100 (1s). $1 stake, 5% growth, TP at $5. Pure volatility bet.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'COIN_FLIP',
    config: {
      strategyType: 'COIN_FLIP',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      riskPerTrade: 5,
      maxPositions: 1,
      dailyLossLimit: 10,
      maxDrawdown: 20,
      coinFlip: {
        growthRate: 0.05,
        stake: 1,
        takeProfitUSD: 0.50,
        maxContracts: 1,
        cooldownSeconds: 5,
        minBalance: 1,
      },
    },
  },
  {
    id: 'v100-1s-conservative',
    name: 'V100 (1s) Conservative',
    description: 'EMA crossover on Volatility 100 (1s). Strict filters, low risk. Good for demo testing.',
    riskLevel: 'LOW',
    timeframe: '1m',
    strategyType: 'CONSERVATIVE',
    config: {
      strategyType: 'CONSERVATIVE',
      symbol: 'V100_1S',
      emaFast: 9,
      emaSlow: 21,
      rsiPeriod: 14,
      rsiOverbought: 70,
      rsiOversold: 30,
      useAtrStops: true,
      atrPeriod: 14,
      atrSlMultiplier: 1.5,
      atrTpMultiplier: 3.0,
      takeProfit: 15,
      stopLoss: 8,
      trailingStop: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      sessionFilterEnabled: false,
      adxThreshold: 20,
      riskPerTrade: 1,
      maxPositions: 1,
      dailyLossLimit: 3,
      maxDrawdown: 10,
      positionSizing: 'percentage',
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
    },
  },
  {
    id: 'rise-fall-r100',
    name: 'Rise/Fall R_100',
    description: 'Binary options on Volatility 100. 5-tick duration, $1 stake. ~95% payout, 50% probability.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'RISE_FALL',
    config: {
      strategyType: 'RISE_FALL',
      symbol: 'V100',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      riseFall: {
        stake: 1,
        durationTicks: 5,
        direction: 'auto',
        maxContracts: 1,
        cooldownSeconds: 3,
        minBalance: 1,
      },
    },
  },
  {
    id: 'even-odd-r100',
    name: 'Even/Odd R_100',
    description: 'Digit options on Volatility 100. True 50/50, ~95% payout. Fast throughput.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'EVEN_ODD',
    config: {
      strategyType: 'EVEN_ODD',
      symbol: 'V100',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      evenOdd: {
        stake: 1,
        durationTicks: 5,
        prediction: 'auto',
        maxContracts: 1,
        cooldownSeconds: 3,
        minBalance: 1,
      },
    },
  },
  {
    id: 'digit-over-safe',
    name: 'Digit Over (Safe)',
    description: 'Digit Over barrier=0 on R_100. 90% win rate, ~10% payout. Like accumulator without compounding.',
    riskLevel: 'MEDIUM',
    timeframe: '1m',
    strategyType: 'DIGIT_OVER_UNDER',
    config: {
      strategyType: 'DIGIT_OVER_UNDER',
      symbol: 'V100',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      digitOverUnder: {
        stake: 1,
        durationTicks: 5,
        direction: 'over',
        barrier: 0,
        maxContracts: 1,
        cooldownSeconds: 3,
        minBalance: 1,
      },
    },
  },

  // ── High-Risk / High-Reward Strategies ──────────────────────────────────────
  {
    id: 'martingale-rise-fall',
    name: 'Martingale Rise/Fall',
    description: 'Double stakes after each loss. One win recovers all. Max 6 losses = $63 risk on $1 base.',
    riskLevel: 'EXTREME',
    timeframe: '1m',
    strategyType: 'MARTINGALE',
    config: {
      strategyType: 'MARTINGALE',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      martingale: {
        baseStake: 1,
        multiplier: 2,
        maxConsecutiveLosses: 6,
        contractType: 'rise_fall',
        durationTicks: 5,
        directionMode: 'auto',
        cooldownSeconds: 3,
        minBalance: 1,
        maxSessionLoss: 50,
        signalEmaFast: 9,
        signalEmaSlow: 21,
      },
    },
  },
  {
    id: 'martingale-signal',
    name: 'Martingale + Signal Filter',
    description: 'Martingale with EMA/RSI signal to bias direction above 50%. Lower blow-up risk than pure random.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'MARTINGALE',
    config: {
      strategyType: 'MARTINGALE',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      martingale: {
        baseStake: 1,
        multiplier: 2,
        maxConsecutiveLosses: 6,
        contractType: 'rise_fall',
        durationTicks: 5,
        directionMode: 'signal',
        cooldownSeconds: 3,
        minBalance: 1,
        maxSessionLoss: 50,
        signalEmaFast: 9,
        signalEmaSlow: 21,
      },
    },
  },
  {
    id: 'accu-ladder-1pct',
    name: 'Accumulator Ladder 1%',
    description: 'Low growth rate (1%) for wide barriers. Let contracts run 60s. 50% profit target.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'ACCUMULATOR_LADDER',
    config: {
      strategyType: 'ACCUMULATOR_LADDER',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      accumulatorLadder: {
        growthRate: 0.01,
        stake: 5,
        maxDurationSeconds: 60,
        targetProfitPercent: 0.5,
        maxContracts: 1,
        cooldownSeconds: 5,
        minBalance: 1,
      },
    },
  },
  {
    id: 'momentum-spam',
    name: 'Momentum Spam R/F',
    description: 'EMA(5/13) filtered rapid-fire Rise/Fall. 5 contracts per burst at $1 each.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'MOMENTUM_RISE_FALL',
    config: {
      strategyType: 'MOMENTUM_RISE_FALL',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      momentumRiseFall: {
        stake: 1,
        durationTicks: 5,
        emaFast: 5,
        emaSlow: 13,
        maxBurstContracts: 5,
        burstIntervalSeconds: 3,
        cooldownSeconds: 10,
        minBalance: 1,
        stopOnSignalFlip: true,
      },
    },
  },
  {
    id: 'digit-sniper-3',
    name: 'Digit Sniper (3 Digits)',
    description: 'DIGITMATCH on 3 digits simultaneously. $0.50/digit = $1.50/round. ~30% hit rate, 900% payout.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'DIGIT_SNIPER',
    config: {
      strategyType: 'DIGIT_SNIPER',
      symbol: 'V100',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      digitSniper: {
        stakePerDigit: 0.50,
        durationTicks: 5,
        targetDigits: [3, 5, 7],
        maxConcurrentRounds: 1,
        cooldownSeconds: 5,
        minBalance: 1,
      },
    },
  },
  {
    id: 'boom500-sniper',
    name: 'Boom 500 Sniper',
    description: 'Buy TURBOSLONG after 10 consecutive drops on Boom 500. Betting on the spike.',
    riskLevel: 'EXTREME',
    timeframe: '1m',
    strategyType: 'VOLATILITY_BREAKOUT',
    config: {
      strategyType: 'VOLATILITY_BREAKOUT',
      symbol: 'BOOM500',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      volatilityBreakout: {
        stake: 5,
        targetIndex: 'BOOM500',
        consecutiveTickThreshold: 10,
        turboDurationMinutes: 5,
        maxContracts: 1,
        cooldownSeconds: 10,
        minBalance: 1,
      },
    },
  },
  {
    id: 'hedged-accu',
    name: 'Hedged Accumulator',
    description: 'Two opposing ACCU contracts. One side compounds while the other gets knocked out. 3% growth.',
    riskLevel: 'HIGH',
    timeframe: '1m',
    strategyType: 'HEDGED_ACCUMULATOR',
    config: {
      strategyType: 'HEDGED_ACCUMULATOR',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      hedgedAccumulator: {
        growthRate: 0.03,
        stakePerSide: 1,
        takeProfitUSD: 2,
        maxPairs: 1,
        cooldownSeconds: 10,
        minBalance: 1,
      },
    },
  },
  {
    id: 'all-in-recovery',
    name: 'All-In Recovery',
    description: 'When balance drops below $60, switch to $15 stakes + 5% growth. Recover or blow up.',
    riskLevel: 'EXTREME',
    timeframe: '1m',
    strategyType: 'ALL_IN_RECOVERY',
    config: {
      strategyType: 'ALL_IN_RECOVERY',
      symbol: 'V100_1S',
      sessionFilterEnabled: false,
      spreadFilterPips: 0,
      minBodyPips: 0,
      tradingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      tradingHoursStart: '00:00',
      tradingHoursEnd: '23:59',
      timezone: 'UTC',
      allInRecovery: {
        triggerBalance: 60,
        recoveryStake: 15,
        recoveryGrowthRate: 0.05,
        recoveryTakeProfitUSD: 2,
        recoveryContractType: 'accumulator',
        maxRecoveryAttempts: 5,
        cooldownSeconds: 5,
        hardStopBalance: 10,
      },
    },
  },
];

export function getPresetById(id: string): TradingPreset | undefined {
  return PRESETS.find((p) => p.id === id);
}
